---
abstract: 'SOAP and WSDL, client side'
author:
  - 'Mark Overmeer'
build_requires:
  ExtUtils::MakeMaker: 0
configure_requires:
  ExtUtils::MakeMaker: 0
dynamic_config: 1
generated_by: 'ExtUtils::MakeMaker version 6.6302, CPAN::Meta::Converter version 2.120921'
license: perl
meta-spec:
  url: http://module-build.sourceforge.net/META-spec-v1.4.html
  version: 1.4
name: XML-Compile-SOAP
no_index:
  directory:
    - t
    - inc
requires:
  File::Slurp: 0
  LWP: 5.816
  Log::Report: 0.9
  Test::Deep: 0.095
  Test::More: 0.54
  Time::HiRes: 0
  XML::Compile: 1.28
  XML::Compile::Cache: 0.992
  XML::Compile::Tester: 0.9
version: 2.34
